#Project Information
site_name: HCL RTist in Code
site_description: >-
  RTist in Code is a Visual Studio Code extension for creating stateful realtime C++ applications consisting of communicating state machines.
site_url: https://opensource.hcltechsw.com/rtist-in-code

#Md and HTML locations in the repository 
site_dir: docs
docs_dir: docs-sources

# Theme Configuration
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: en
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
  custom_dir: theme_overrides/
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono

  # Static files
  static_templates:
    - 404.html


# Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
#  - pymdownx.superfences
  - pymdownx.keys
  - attr_list

extra:
  analytics: 
    provider: custom
    property: UA-169645537-2
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HCL-TECH-SOFTWARE
  version:
    provider: mike


copyright: >-
  Copyright &copy; 2022, HCL Technologies Limited.

# Repository
repo_url: https://github.com/HCL-TECH-SOFTWARE/rtist-in-code
repo_name: hcl-software/rtist-in-code
edit_uri: edit/main/docs-sources


# Customization
extra_css:
  - stylesheets/style.css
  - stylesheets/prism.css

extra_javascript:
  - scripts/prism.js

plugins:
  - search
  - markdownextradata:
      jinja_options:
          variable_start_string: '{$'
          variable_end_string: '$}'

extra:
  product:
    name: RTist in Code
  rtist:
    name: HCL RTist

 #Table of contents 
nav:
  - Home: index.md
  - Documentation:   
     - Overview: overview.md
     - Installing: installing.md
     - The Art Language: art-lang.md
     - Working with Art: 
        - Working with Art: working-with-art/index.md
        - Text Editor: working-with-art/art-editor.md
        - Diagrams: working-with-art/diagrams.md
        - Outline View: working-with-art/outline-view.md
        - References View: working-with-art/references.md
     - Validation: validation.md
     - Target RunTime System: 
        - Target RunTime System: target-rts/index.md
        - C++ API: https://rtist.hcldoc.com/help/topic/com.hcl.xtools.umldt.rt.targetrts.doc.isv/html/index.html
     - Building: 
        - Building: building/index.md
        - Transformation Configurations: building/transformation-configurations.md
        - Art Compiler: building/art-compiler.md     
  - Notices: notices.md

